export const TYPES = {
    Application: Symbol.for('Application'),
    ILogger: Symbol.for('ILogger'),
    PrismaService: Symbol.for('PrismaService'),
    ExeptionFilter: Symbol.for('ExeptionFilter'),
    ConfigService: Symbol.for('ConfigService'),
    UsersController: Symbol.for('UsersController'),
    UsersServices: Symbol.for('UsersServices'),
    BoardsController: Symbol.for('BoardsController'),
    BoardsServices: Symbol.for('BoardsServices'),
    ColumnsController: Symbol.for('ColumnsController'),
    ColumnsServices: Symbol.for('ColumnsServices'),
    CardsController: Symbol.for('CardsController'),
    CardsServices: Symbol.for('CardsServices'),
    Websocket: Symbol.for('Websocket'),
    WsBoardController: Symbol.for('WsBoardController'),
}